M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Mon 07 Aug 2023 10:55:55 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-07T10:55:55+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X142.011Y-108.754
X148.501Y-97.504
X155.001Y-108.754
T0
M30
