M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Fri 04 Aug 2023 05:54:08 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-04T05:54:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C1.000
%
G90
G05
T1
X144.945Y-105.001
X152.057Y-105.001
T0
M30
