M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Fri 04 Aug 2023 04:27:59 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-04T04:27:59+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X145.961Y-110.076
X148.501Y-110.076
X151.041Y-110.076
T2
X148.501Y-101.194
T0
M30
