M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Thu 03 Aug 2023 22:15:38 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-03T22:15:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X145.961Y-108.052
X148.501Y-108.052
X151.041Y-108.052
T2
X148.501Y-102.21
T0
M30
