M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Mon 07 Aug 2023 13:19:24 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-07T13:19:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.016
%
G90
G05
T1
X152.946Y-102.464
X152.946Y-105.004
X152.946Y-107.544
T0
M30
