M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date Sun 06 Aug 2023 23:36:56 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-06T23:36:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.794
%
G90
G05
T1
X148.501Y-100.813
X148.501Y-109.195
T0
M30
